### ISSUE TITLE
Add Datapoint to trigger Data request

### ISSUE THREAD

**Issue by Linedancer** [Jey-Cee/ioBroker.primelab#17]
It is not important to check every several minutes if the are new Values on the cloud. I would suggest to have a trigger to get data from the cloud instead of using cron.

**Comment by Jey-Cee** [comment]
You can change the cron in expert mode in instance view. To use a trigger parallel to cron the adapter has to run as daemon. This causes permanently RAM consumption. Also you can start/stop the Adapter via js, wait for updating the values and stop it. 

For now i will not implement a trigger.

**Comment by Linedancer** [comment]
OK, understood.
Will try to start and stop the Adapter.


Ciao
Gerhard
Phone: +49 172 6731765
Mail: g.boeke@boeke24.de

________________________________
Von: Jey-Cee <notifications@github.com>
Gesendet: Friday, August 9, 2019 4:47:30 PM
An: Jey-Cee/ioBroker.primelab <ioBroker.primelab@noreply.github.com>
Cc: Linedancer <heizer21@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Jey-Cee/ioBroker.primelab] Add Datapoint to trigger Data request (#17)


You can change the cron in expert mode in instance view. To use a trigger parallel to cron the adapter has to run as daemon. This causes permanently RAM consumption. Also you can start/stop the Adapter via js, wait for updating the values and stop it.

For now i will not implement a trigger.

**Comment by Jey-Cee** [comment]
Additional information for you: There is a Object to control the state of the Adapter, see screenshot.
![image](https://user-images.githubusercontent.com/16007760/62832580-20ba2400-bc31-11e9-836e-5183c11a70fc.png)
This will activate or deactivate the adapter, if it is activated the adapter is running as cron, so you have to wait for the normal start and than deactivate it after the values are updatet.
